### PR TITLE
Resolve compilation errors on pi3 b+

### LINKED ISSUE #2: Compiling Errors
Trying to use this library on a Raspberry Pi 2, but when I compile the code I have some issues
Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

**1- Makefile** SOLVED
Change M=$(PWD) to M=$(shell pwd)

**2- Compiling** ERRORS
pi@raspberrypi:~/keybus $ sudo make
make -C /lib/modules/4.14.34-v7+/build M=/home/pi/keybus modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.34-v7+'
  CC [M]  /home/pi/keybus/keybus-dev.o
  CC [M]  /home/pi/keybus/keybus-protocol.o
/home/pi/keybus/keybus-protocol.c: In function ‘parse_A5’:
/home/pi/keybus/keybus-protocol.c:195:9: error: assignment to expression with array type
   extra = " error (possibly battery)";
         ^
/home/pi/keybus/keybus-protocol.c:197:9: error: assignment to expression with array type
   extra = " error resolved";
         ^
/home/pi/keybus/keybus-protocol.c:201:9: error: assignment to expression with array type
   extra = " PGM2 (*72)";
         ^
/home/pi/keybus/keybus-protocol.c:203:9: error: assignment to expression with array type
   extra = " armed (stay)";
         ^
/home/pi/keybus/keybus-protocol.c:205:9: error: assignment to expression with array type
   extra = " armed (away)";
         ^
scripts/Makefile.build:328: recipe for target '/home/pi/keybus/keybus-protocol.o' failed
make[2]: *** [/home/pi/keybus/keybus-protocol.o] Error 1
Makefile:1528: recipe for target '_module_/home/pi/keybus' failed
make[1]: *** [_module_/home/pi/keybus] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.34-v7+'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

### PR DESCRIPTION
**Pull request by erichoog**
Hope this receives you well.

This commit resolves the compilation errors I received on the Raspberry Pi 3 B+.  It resolves #2 

I am working on fully testing as working on the hardware interface at the moment but thought this might help.

This may cause breaking changes for the pi 2 version you have previously tested with.

### CODE REVIEW

**Comment by erichoog** [comment]
Can confirm this is working on Raspberry Pi 3 B+.  

Had to rename keybusdev-overlay.dtb file to keybusdev-overlay.dtbo in /boot/overlays dir and add dtoverlay=keybusdev-overlay to the /boot/config.txt file and reboot as well to get it working.

Will open a second pull request to update the README.md for that.

**Comment by erichoog** [comment]
Added everything including update to README.md and .dts file to this PR

**Comment by hvesalai** [comment]
@erichoog somehow I had missed this PR. Thank you, now merged!

Did it work otherwise?

**Comment by erichoog** [comment]
> @erichoog somehow I had missed this PR. Thank you, now merged!
> 
> Did it work otherwise?

Hey yes it did work as expected from what you had posted about it.  I got side tracked from the project a bit but just need to write something to consume the data. Thanks again!

**Pull request merged**
